"""Hand-set center/front/rear cases, independent of simulator settlement."""
from copy import deepcopy
import unittest
from unittest.mock import patch

from test_baseline import ROOT
from test_coordination import unit
from agent import phase_maintenance as pm, phase_supply, nightwork, strategy_config, home_defense
from agent.protocol import Turn, Pos, WALL_FIXER

# Explicit geometry, not generated by the wall selector being tested.
GEOMETRY = {
    'E': ((9,10), (12,9), (12,8), (12,7), (7,9), (11,9)),
    'W': ((30,10), (28,9), (28,8), (28,7), (33,9), (29,9)),
    'N': ((20,6), (20,8), (19,8), (18,8), (20,3), (20,7)),
    'S': ((20,25), (20,22), (19,22), (18,22), (20,27), (20,23)),
}


def observation(direction='E', center_hp=550, outer_hp=400):
    base, center, outer, corner, rear, worker = GEOMETRY[direction]
    p = dict(roundNo=461, mapInfo=dict(width=41,height=32,zones=[]),
             teamOur=dict(type='challenger' if direction in ('E','N') else 'defender', goldNum=100,
                          roles=[unit(1,'worker',*worker), unit(4,'station',*base,1500),
                                 unit(10,'wall',*center,center_hp), unit(11,'wall',*outer,outer_hp),
                                 unit(12,'wall',*corner,450), unit(13,'wall',*rear,50)]),
             teamEnemy=dict(roles=[]), robot=dict(roles=[]))
    p['teamOur']['roles'][0]['backpack']=[WALL_FIXER]*3
    return p


class CenterMaintenanceTests(unittest.TestCase):
    def setUp(self):
        self.config=deepcopy(strategy_config.DEFAULTS)
        setting=patch.object(strategy_config,'get',return_value=self.config)
        setting.start();self.addCleanup(setting.stop)

    def plan(self,p,memory=None):
        return pm.night_plan(Turn.load(p),{} if memory is None else memory,{},
                             config=self.config['maintenance'],payload=p)

    def test_all_approaches_center_first_under_shared_entry_threshold(self):
        for direction in GEOMETRY:
            with self.subTest(direction=direction):
                p=observation(direction)
                result=self.plan(p)
                self.assertEqual(result['report']['target'],10)
                self.assertEqual(result['commands'][1]['targetPos'],[Pos(*GEOMETRY[direction][1]).dump()])
                self.assertEqual(result['commands'][1]['action'],'use')
                # Center must qualify; a healthy center cannot suppress the outer wall.
                p['teamOur']['roles'][2]['health']=551
                self.assertEqual(self.plan(p)['report']['target'],11)

    def test_critical_outer_beats_ordinary_center_and_rear_is_never_candidate(self):
        for direction in GEOMETRY:
            p=observation(direction,outer_hp=200)
            self.assertEqual(self.plan(p)['report']['target'],11)
            p['teamOur']['roles']=p['teamOur']['roles'][:2]+[p['teamOur']['roles'][-1]]
            self.assertFalse(self.plan(p)['commands'])

    def test_existing_ordinary_lease_retargets_reachable_emergency_after_feedback(self):
        p=observation();memory={}
        first=self.plan(p,memory);pm.finalize(memory,first,first['commands'])
        # Same observation cannot issue a second repair or alter its target.
        p['teamOur']['roles'][3]['health']=100
        self.assertFalse(self.plan(p,memory)['commands'])
        self.assertEqual(memory['lease']['target'],10)
        p['roundNo']+=1;p['teamOur']['roles'][0]['backpack'].pop()
        p['teamOur']['roles'][2]['health']=700
        p['lastRoundRoleActionResults']={'1':True}
        result=self.plan(p,memory)
        self.assertEqual(result['report']['use_feedback'],'confirmed')
        self.assertEqual(result['report']['retarget_reason'],'reachable_wall_emergency')
        self.assertEqual(memory['lease']['target'],11)
        self.assertEqual(memory['lease']['home'],Pos(*GEOMETRY['E'][-1]).dump())

    def test_unconfirmed_use_does_not_retarget_and_return_lease_is_not_stolen(self):
        p=observation();memory={};first=self.plan(p,memory)
        pm.finalize(memory,first,first['commands'])
        p['roundNo']+=1;p['teamOur']['roles'][3]['health']=100
        result=self.plan(p,memory)
        self.assertEqual(result['report']['use_feedback'],'unconfirmed')
        self.assertNotIn('retarget_reason',result['report'])
        self.assertFalse(result['commands'])

    def test_old_rear_lease_returns_inside_and_releases_without_spending(self):
        p=observation();p['teamOur']['roles'][0]['pos']=dict(x=8,y=9)
        memory={'last_round':460,'lease':dict(owner=1,target=13,home=dict(x=8,y=10),
                  phase='repair',issued_round=460)}
        result=self.plan(p,memory)
        self.assertEqual(result['report']['released_target_reason'],'rear_wall_no_longer_maintained')
        self.assertEqual(result['commands'][1]['action'],'move')
        self.assertTrue(home_defense.inside(Turn.load(p),Pos.load(result['commands'][1]['targetPos'][0])))
        self.assertEqual(memory['lease']['phase'],'return')
        pm.finalize(memory,result,result['commands'])
        p['roundNo']+=1;p['teamOur']['roles'][0]['pos']=dict(x=8,y=10)
        result=self.plan(p,memory)
        self.assertEqual(result['report']['reason'],'returned_observed')
        self.assertNotIn('lease',memory)
        self.assertFalse(result['commands'])
        self.assertEqual(len(p['teamOur']['roles'][0]['backpack']),3)

    def test_disabled_policy_retains_legacy_rear_repair(self):
        self.config['enabled']=False
        p=observation();p['teamOur']['roles'][0]['pos']=dict(x=8,y=9)
        p['teamOur']['roles']=p['teamOur']['roles'][:2]+[p['teamOur']['roles'][-1]]
        self.assertEqual(self.plan(p)['commands'][1]['action'],'use')

    def test_blocked_rear_return_keeps_owner_without_wall_use_or_outside_move(self):
        p=observation();p['teamOur']['roles'][0]['pos']=dict(x=8,y=9)
        p['teamOur']['roles'].append(unit(90,'worker',8,10))
        memory={'last_round':460,'lease':dict(owner=1,target=13,home=dict(x=8,y=10),
                  phase='repair',issued_round=460)}
        result=self.plan(p,memory)
        self.assertEqual(result['owned_roles'],[1])
        self.assertEqual(result['report']['reason'],'return_blocked')
        self.assertEqual(memory['lease']['phase'],'return')
        self.assertFalse(result['commands'])

    def test_active_emergency_and_return_lease_do_not_oscillate_to_center(self):
        for phase in ('repair','return'):
            p=observation(center_hp=100,outer_hp=200)
            memory={'last_round':460,'lease':dict(owner=1,target=11,home=dict(x=11,y=10),
                      phase=phase,issued_round=460)}
            result=self.plan(p,memory)
            self.assertEqual(memory['lease']['target'],11)
            self.assertEqual(memory['lease']['phase'],phase)
            self.assertNotIn('retarget_reason',result['report'])

    def test_quiet_night_maintenance_uses_center_then_critical_outer_and_excludes_rear(self):
        p=observation(center_hp=650)
        turn=Turn.load(p);worker=turn.workers()[0]
        choices=[pos for item,pos in nightwork._maintenance(turn,worker) if item==WALL_FIXER]
        self.assertEqual(choices[:2],[Pos(12,9),Pos(12,8)])
        p['teamOur']['roles'][3]['health']=100
        turn=Turn.load(p)
        choices=[pos for item,pos in nightwork._maintenance(turn,turn.workers()[0]) if item==WALL_FIXER]
        self.assertEqual(choices[0],Pos(12,8))
        p['teamOur']['roles'][0]['pos']=dict(x=8,y=9)
        turn=Turn.load(p)
        choices=list(nightwork._maintenance(turn,turn.workers()[0]))
        self.assertNotIn(Pos(7,9),[pos for _,pos in choices],
                         'rear wall is not upgraded or repaired during quiet work')
        self.assertIn(('StationUpgradeVoucher1',Pos(9,10)),choices,
                      'removing rear investment must preserve base-upgrade options')

    def test_night_adjacent_repair_priorities_with_guard_still_present(self):
        for hp,target in ((400,Pos(12,9)),(100,Pos(12,8))):
            p=observation(outer_hp=hp)
            p['teamOur']['roles'] += [unit(2,'worker',10,8),unit(20,'rocket',11,10,1000),unit(21,'rocket',11,8,1000)]
            turn=Turn.load(p);workers={u.unit_id:u for u in turn.workers()};guns={u.unit_id:u for u in turn.weapons()}
            result=nightwork._front_repair(turn,((workers[1],guns[20]),(workers[2],guns[21])))
            self.assertEqual(result,{1:dict(action='use',name=WALL_FIXER,targetPos=[target.dump()])})

    def test_survival_stock_is_reserved_before_weapon_budget(self):
        from test_user_phase_integration import observation as stock_board
        p=stock_board();p['teamOur']['roles'][-1]['pos']=dict(x=7,y=10)
        p['teamOur']['roles'][-1]['health']=100
        with patch.object(phase_supply.upgrade_itinerary,'weapon_reserve',return_value={'gold':150}):
            proposal,report=phase_supply.plan(Turn.load(p),p,{},deadline=67)
            self.assertEqual(proposal,(2,dict(action='buy',name=WALL_FIXER,num=2)))
            self.assertEqual(report['reason'],'prepare_night_repair_stock')
            # Same known damage at a front wall permits the existing emergency exception.
            p['teamOur']['roles'][-1]['pos']=dict(x=12,y=10)
            proposal,report=phase_supply.plan(Turn.load(p),p,{},deadline=67)
            self.assertEqual(proposal,(2,dict(action='buy',name=WALL_FIXER,num=2)))


if __name__=='__main__':unittest.main()
