"""Independent hand-set expectations for R01/R04 and user S06 local model."""
import unittest
from test_defense_layout import board, unit, REPORTED, MIRROR
from test_robot_wall_screen import advance, with_worker
from test_robots import board as robot_board
from agent import brain, pioneer_safety
from agent.protocol import Turn, Pos, distance


def guns():
    p = board(round_no=90)
    p['teamOur']['roles'] = [unit(1,'station',9,22,1500),
        unit(2,'worker',11,21,220),unit(3,'worker',8,20,220),unit(4,'pioneer',8,23,200),
        unit(10,'rocket',11,20),unit(11,'railgun',8,21),unit(12,'rocket',11,22)]
    p['robot']={'roles':[dict(id=90,roleType='largeRobot',health=500,pos=dict(x=15,y=21))]}
    return p


class SharedGunTests(unittest.TestCase):
    def test_new_layout_has_empty_common_inner_stand_both_sides(self):
        for base in (REPORTED,MIRROR):
            turn=Turn.load(board(base=base)); sites=brain._tower_sites(turn)
            self.assertEqual(len(sites),3)
            a,b=sites[0],sites[2]
            stands=[Pos(x,y) for x in range(base[0]-1,base[0]+3)
                    for y in range(base[1]-2,base[1]+2)
                    if Pos(x,y) not in sites and Pos(x,y) not in turn.footprint(turn.station())
                    and distance(Pos(x,y),a)==distance(Pos(x,y),b)==1]
            self.assertTrue(stands,(base,sites))

    def test_one_worker_alternates_rocket_a_b_after_three_round_cooldown(self):
        p=guns()
        # Explicit official cooldown observations, not generated by planner/simulator.
        for index,(ca,cb,expected) in enumerate([(0,0,10),(3,0,12),(2,3,None),(1,2,None),(0,1,10),(3,0,12)]):
            p['roundNo']=90+index
            p['teamOur']['roles'][4]['cooldown']=ca;p['teamOur']['roles'][6]['cooldown']=cb
            turn=Turn.load(p);cmd={};brain._night(turn,cmd,p);brain._fill_ready_weapons(turn,cmd,set())
            fired=[uid for uid,c in cmd.items() if uid in (10,12) and c['action']=='attack']
            self.assertEqual(fired,[] if expected is None else [expected])
            if fired:self.assertEqual(cmd[fired[0]]['controllerId'],'2')
            self.assertNotIn(2,cmd)

    def test_daytime_preparation_cannot_fire_at_visible_robots(self):
        p=guns();p['roundNo']=65
        turn=Turn.load(p);cmd={};brain._night(turn,cmd,p);brain._fill_ready_weapons(turn,cmd,set())
        self.assertFalse(any(c['action']=='attack' for c in cmd.values()))

    def test_distant_existing_rockets_keep_ordinary_fallback(self):
        p=guns();p['teamOur']['roles'][6]['pos']=dict(x=8,y=23)
        self.assertIsNone(brain._coordinate_rockets(Turn.load(p),{},set()))

    def test_busy_controller_is_not_overwritten(self):
        p=guns();p['teamOur']['roles']=[r for r in p['teamOur']['roles'] if r['id']!=3]
        command={'action':'use','name':'WallFixer','targetPos':[dict(x=12,y=21)]}
        cmd={2:command};self.assertIsNone(brain._coordinate_rockets(Turn.load(p),cmd,set()))
        self.assertEqual(cmd[2],command)


class TargetAndSafetyTests(unittest.TestCase):
    def test_far_role_does_not_lure_monster_away_from_base(self):
        for side in ('challenger','defender'):
            p=with_worker(robot_board(robot_pos=(6,5),wall_pos=None),pos=(1,5),side=side)
            out=advance(p)
            move=out['frame']['robotMoves'][0]
            self.assertEqual(move['to']['x'],7)  # Base is to the right; worker is left.
            self.assertEqual(out['frame']['robotAttacks'],[])

    def test_near_role_is_attacked_at_range_three(self):
        p=with_worker(robot_board(robot_pos=(6,5),wall_pos=None),pos=(3,5))
        out=advance(p)
        self.assertEqual(out['frame']['robotAttacks'][0]['victim'],10010)
        self.assertEqual(out['frame']['robotAttacks'][0]['damage'],5)

    def test_pioneer_vetoes_walk_into_range_but_wall_can_screen(self):
        p=guns();hero=p['teamOur']['roles'][3];hero['pos']=dict(x=20,y=20)
        p['robot']['roles'][0]['pos']=dict(x=24,y=20)
        cmd={4:dict(action='move',targetPos=[dict(x=21,y=20)])}
        result=pioneer_safety.override(Turn.load(p),cmd)
        self.assertIsNotNone(result);self.assertEqual(result['after'],0)
        p['teamOur']['roles'].append(unit(30,'wall',22,20))
        self.assertIsNone(pioneer_safety.override(Turn.load(p),cmd))

    def test_reducing_exposure_retreat_preserved(self):
        p=guns();p['teamOur']['roles'][3]['pos']=dict(x=20,y=20)
        p['robot']['roles'][0]['pos']=dict(x=23,y=20)
        cmd={4:dict(action='move',targetPos=[dict(x=19,y=20)])}
        self.assertIsNone(pioneer_safety.override(Turn.load(p),cmd))

    def test_daytime_unchanged(self):
        p=guns();p['roundNo']=10
        self.assertIsNone(pioneer_safety.override(Turn.load(p),{}))


if __name__=='__main__':unittest.main()
