"""Hand-authored local task fixtures; model/strategy never import this module.

Correct results are independently enumerated below, not generated by the
solver. These are engineering tests, not leaked official tasks or certification.
"""
from copy import deepcopy


CASES = (
    {
        'id': 'weather-doc-v1-beijing',
        'description': '阅读 /brief 中的接口文档，查询北京天气。严格返回 JSON 对象，'
                       '仅包含 city（字符串）和 temperature（整数），不要解释或 Markdown。',
        'answer': '{"city":"北京","temperature":23}', 'grading': 'json_fields',
        'sandbox_fixture': {'cwd': '/workspace',
            'files': {'/brief/README.txt': '离线天气查询：python3 /svc/weather.py --city 城市。'
                      '支持北京、上海；返回记录数组。请提取题目要求的对象。'},
            'programs': {'/svc/weather.py': {'filters': ['city'], 'required_filters': ['city'],
                'records': [{'city': '北京', 'temperature': 23}, {'city': '上海', 'temperature': 29}],
                'output_fields': ['city', 'temperature']}}},
    },
    {
        'id': 'weather-doc-v2-shanghai',
        'description': '阅读 /manual 中的接口说明。查询上海天气。只返回 JSON 对象，'
                       '包含 city（字符串）和 temperature（整数）。接口可能与以前不同。',
        'answer': '{"city":"上海","temperature":17}', 'grading': 'json_fields',
        'sandbox_fixture': {'cwd': '/workspace',
            'files': {'/manual/service.txt': '接口版本 v2：python3 /service/query.py --place 城市。'
                      '输出字段按 temperature、city 排列，输出为单条记录数组。'},
            'programs': {'/service/query.py': {'filters': ['place'], 'required_filters': ['place'],
                'records': [{'place': '上海', 'city': '上海', 'temperature': 17},
                            {'place': '北京', 'city': '北京', 'temperature': 31}],
                'output_fields': ['temperature', 'city']}}},
    },
    {
        'id': 'decimal-aggregation',
        'description': '阅读 /docs 的账目查询说明，求 A 区金额之和。只返回保留一位小数的数字字符串，'
                       '不包含引号、单位或其他文字。',
        'answer': '0.3', 'grading': 'exact',
        'sandbox_fixture': {'cwd': '/workspace',
            'files': {'/docs/accounts.txt': '离线账目汇总：python3 /tools/sum.py --zone 区域。'
                      '返回 JSON 的 total 字段为精确十进制字符串。'},
            'programs': {'/tools/sum.py': {'operation': 'sum', 'filters': ['zone'],
                'required_filters': ['zone'], 'value_field': 'amount',
                'records': [{'zone': 'A', 'amount': '0.1'}, {'zone': 'A', 'amount': '0.2'},
                            {'zone': 'B', 'amount': '91.7'}]}}},
    },
)


PIPELINE_CASES = (
    {
        'id': 'nested-api-15-rounds',
        'description': '请阅读task_delta.md，获取任务信息',
        'answer': '{"city":"丙地","value":17}', 'grading': 'json_fields',
        'timeout_rounds': 15, 'score_reward': 80, 'gold_reward': 80,
        'sandbox_fixture': {'cwd': '/', 'files': {
            '/tmp/changed/work/task_delta.md': '阅读同目录API_DOCS.md，查询丙地；只返回JSON字段city和value。',
            '/tmp/changed/work/API_DOCS.md': 'python3 /svc/catalog.py --place 城市，返回记录数组。接口与其它任务可能不同。'},
            'programs': {'/svc/catalog.py': {'filters': ['place'], 'required_filters': ['place'],
                'records': [{'place': '丙地', 'city': '丙地', 'value': 17},
                            {'place': '丁地', 'city': '丁地', 'value': 91}],
                'output_fields': ['city', 'value']}}},
    },
)


def install(state, case_ids=None):
    """Explicitly enable a local suite before acceptance; default games unchanged."""
    selected = list(case_ids) if case_ids is not None else [c['id'] for c in CASES]
    by_id = {c['id']: c for c in CASES + PIPELINE_CASES}
    if not selected or any(key not in by_id for key in selected):
        raise ValueError('unknown or empty local task suite')
    world = (state.get('_demo') or {}).get('task_world')
    if not world or any(p.get('active') for p in world['points'].values()):
        raise ValueError('install before starting a task')
    world['agent_cases'] = deepcopy([by_id[key] for key in selected])
    return state
